### ISSUE TITLE
AATAMS

### ISSUE THREAD

**Issue by bhasin85** [bhasin85/aodn#15]
1. Install git and curl
1. Clone repository
    `$ git clone https://github.com/aodn/aatams.git`
1. Switch to aatams project directory
    `$ cd aatams`
1. Install [SDKMAN](http://sdkman.io/install.html)
1. Install Grails
    `$ sdk use grails 1.3.7`
1. Install Java
    `$ sdk use java 6u93-zulu`
1. Install [Postgres](http://postgresguide.com/setup/install.html) and [PostGIS](http://postgis.net/install/)
1. Setup database (see the content of init-db.sh below)
    Create init-db.sh and run it using `$ sudo -u postgres ./init_db.sh`
1. Running app for local development 
    `$ grails clean`
    `$ grails run-app`
1. Running test 
    `$ grails clean`
    `$ sudo -u postgres ./init_test_db.sh`
    `$ grails test-app --echoOut`

## init-db.sh 
```
PSQL_ARGS=${1:--U postgres}
psql $PSQL_ARGS -c "drop database if exists aatams" || exit
psql $PSQL_ARGS -c "drop user if exists aatams" || exit
psql $PSQL_ARGS -c "create user aatams unencrypted password 'aatams'" || exit
psql $PSQL_ARGS -c "create database aatams owner aatams" || exit
psql $PSQL_ARGS -c "create extension postgis" aatams || exit
psql $PSQL_ARGS -c "create schema aatams authorization aatams" aatams || exit
psql $PSQL_ARGS -c "alter database aatams set search_path to 'aatams', 'public'" aatams || exit
psql $PSQL_ARGS -c "alter database aatams set timezone to 'Australia/Hobart'" aatams || exit

```

~~## Setting up database for integration tests~~

~~`sudo -u postgres./init_test_db.sh `~~

**Comment by xhoenner** [comment]
Awesome, thanks @bhasin85, it mostly worked for me. A few additional things that I had to do, some may be fairly obvious:
  * before step 6, need to clone the aatams GitHub repository by running `https://github.com/aodn/aatams.git`
  * The link to the Postgres install doesn't work due to a missing `.html` at the end of the URL.
  * Had to install Java (`sudo apt-get install default-jdk`) and fiddle with the `JAVA_HOME` and `GRAILS_HOME` paths before I could get 6 to run successfully, see https://stackoverflow.com/a/5258928

**Comment by xhoenner** [comment]
And got the following error when running 6 and the last of the three commands on step 7:

`java.lang.NullPointerException: Cannot invoke method getAt() on null object
	at _PluginDependencies_groovy$_run_closure5_closure40.doCall(_PluginDependencies_groovy:270)
	at _PluginDependencies_groovy$_run_closure5_closure40.doCall(_PluginDependencies_groovy)
	at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:280)
	at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
	at _PluginDependencies_groovy$_run_closure5.doCall(_PluginDependencies_groovy:268)
	at _GrailsPackage_groovy$_run_closure2.doCall(_GrailsPackage_groovy:167)
	at TestApp$_run_closure6.doCall(TestApp:150)
	at TestApp$_run_closure9.doCall(TestApp:314)
	at TestApp$_run_closure9.doCall(TestApp)
	at TestApp$_run_closure1_closure21.doCall(TestApp:184)
	at TestApp$_run_closure1.doCall(TestApp:174)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at gant.Gant.executeTargets(Gant.groovy:589)
Error loading plugin manager: Cannot invoke method getAt() on null object`
